### ISSUE TITLE
Why configuration is not its own file?

### ISSUE THREAD

**Issue by salastro** [DAFF0D11/xciao#1]
All suckless and most suckless-like projects separate the configuration into its own `config.h` or `config.def.h` file. I do not see a reason for not doing it in this project.

**Comment by DAFF0D11** [comment]
I don't have any real reason apart from 2 files is more complex than 1 file. Perhaps if the project grows considerably it may be necessary to break it out in to multiple files. As it is now, I don't really see the point in following convention for conventions sake.

**Comment by salastro** [comment]
Fair enough. I will close this issue at the moment since there is nothing else that needs to be discussed until the project is complex enough and/or has complex patches, which is not likely in the near future.
