### ISSUE TITLE
Auto-generate sxkhd file

### ISSUE THREAD

**Issue by salastro** [DAFF0D11/xciao#2]
Currently, the sxhkd hotkeys should be written manually, a process full of possible human errors. I have written the following "dirty" script to automate this task. I am not skilled with shell scripting so it is mainly vim macros. Additionally, it depends on having a separate config file for keybinds, although it can be easily tweaked to work on the full `xciao.c` file. 

**THIS IS AN EXPERIMENTAL SCRIPT, RUN AT YOUR OWN RISK**

```diff
diff --git a/.gitignore b/.gitignore
index cad37b7..bb95a60 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1 +1,3 @@
 xciao
+sxhkd
diff --git a/Makefile b/Makefile
index 96c3410..51dfeb1 100644
--- a/Makefile
+++ b/Makefile
@@ -9,9 +9,10 @@ LIBS = -lX11
 
 all:
 	$(CC) $(SRC) $(LIBS) -o $(TARGET)
+	./config-to-sxhkd.sh
 
 clean:
-	rm $(TARGET)
+	rm -f $(TARGET) sxhkd
 
 install:
 	mkdir -p $(DESTDIR)$(PREFIX)/bin
diff --git a/config-to-sxhkd.sh b/config-to-sxhkd.sh
new file mode 100755
index 0000000..6d84a6a
--- /dev/null
+++ b/config-to-sxhkd.sh
@@ -0,0 +1,17 @@
+#!/usr/bin/env sh
+
+CONFIG="config.h"
+FILE="sxhkd"
+
+cp $CONFIG $FILE
+
+sed -i '1,2d;$d' $FILE
+sed -i '$d' $FILE
+sed -i -r '/^\s*$/d' $FILE
+vim -n -u NONE -s macro1.vim $FILE
+sort -r -u -o $FILE $FILE
+sed -i 'p' $FILE
+echo >> $FILE
+vim -n -u NONE -s macro2.vim $FILE
+
+# cat $FILE
diff --git a/macro1.vim b/macro1.vim
new file mode 100644
index 0000000..79bc205
--- /dev/null
+++ b/macro1.vim
@@ -0,0 +1,5 @@
+ggVG:norm df,$d3F,x
+:%s/,\s*/ 
+ggVG:norm Ixciao 
+0ggr	
+:wq
diff --git a/macro2.vim b/macro2.vim
new file mode 100644
index 0000000..6714239
--- /dev/null
+++ b/macro2.vim
@@ -0,0 +1,5 @@
+qq<<0daw:s/"//g
+:s/ / + /
+:s/ControlMask/control/e
+:s/Mod1Mask/alt/e
+2jq1000@q:wq
diff --git a/sxhkd b/sxhkd
deleted file mode 100644
index 3852738..0000000
--- a/sxhkd
+++ /dev/null
@@ -1,43 +0,0 @@
-# Previous tab
-control + j
-    xciao "ControlMask" "j"
-
-# Next tab
-control + k
-    xciao "ControlMask" "k"
-
-# Home page
-control + h
-    xciao "ControlMask" "h"
-
-# Scroll down half page
-control + d
-    xciao "ControlMask" "d"
-
-# Scroll up half page
-control + u
-    xciao  "ControlMask" "u"
-
-# Forward history
-control + bracketleft
-    xciao "ControlMask" "bracketleft"
-
-# Backwards history
-control + bracketright
-    xciao "ControlMask" "bracketright"
-
-# Left arrow key
-alt + h
-    xciao "Mod1Mask" "h"
-
-# Down arrow key
-alt + j
-    xciao "Mod1Mask" "j"
-
-# Up arrow key
-alt + k
-    xciao "Mod1Mask" "k"
-
-# Right arrow key
-alt + l
-    xciao "Mod1Mask" "l"
```

**Comment by DAFF0D11** [comment]
The use of sxhkd was mostly a way for people to try out the project without having to integrate it with their environment, not necessarily the definitive way it should be used. I imagine people would eventually want to just directly call it from say, i3, xfce, dwm, if they find it useful, and would then not need sxhkd as an additional dependency after that.

That said, this is a pretty cool idea, perhaps people will find this issue helpful in their own implementations, thank you for sharing this!

**Comment by salastro** [comment]
I think then it will be helpful to have some scripts that convert `xciao` configuration into the target configuration bundled with the project; maybe a directory named `generate` to contain scripts like this will make stuff easier.

**Comment by DAFF0D11** [comment]
This is outside the scope of the project. Creating generator scripts for every imaginable environment that run reliably on most systems (without breaking things) would quickly turn this simple minimal tool in to a lot of work on a feature the tool was never meant to facilitate.
